# Generated by Django 3.2.18 on 2023-10-10 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_adm',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
