# Generated by Django 3.2.18 on 2023-10-14 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20231014_1222'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transaction',
            new_name='TransactionHistory',
        ),
    ]
