# Generated by Django 3.2.18 on 2023-10-14 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_rename_transaction_transactionhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionhistory',
            name='init_balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transactionhistory',
            name='new_balance',
            field=models.IntegerField(default=0),
        ),
    ]
