# Generated by Django 4.2.7 on 2023-12-11 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_parent_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='cumilative_deposit',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='cumilative_withdraw',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
