# Generated by Django 4.2.7 on 2023-12-11 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_student_cumilative_deposit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='cumilative_deposit',
            field=models.IntegerField(blank=True, default=models.IntegerField(blank=True, null=True), null=True),
        ),
    ]
