# Generated by Django 4.2.7 on 2024-01-28 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_rollcall_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionhistory',
            name='time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
