# Generated by Django 5.0.1 on 2024-01-30 09:57

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_transactionhistory_time_delete_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
